### PR TITLE
SDK33

### PR DESCRIPTION
**Pull request by tsapeta**
PR containing shell and adhoc app tarballs urls for SDK33

### CODE REVIEW

**Comment by sjchmiela** [comment]
Android is being deployed to production Turtles

**Comment by dereknelson** [comment]
@sjchmiela hey! any eta on when iOS will be deployed?

**Comment by tsapeta** [comment]
@dereknelson I've just deployed iOS too 😉

**Comment by dereknelson** [comment]
@tsapeta bless your heart :') how long do you think it will be before we can build 33 ipas?

**Comment by mackbrowne** [comment]
How long until this will be available?  Is there a way I can use it in my CI now?

**Comment by sjchmiela** [comment]
You should be able to run `expo build:{platform}` without any problems now, like you would do normally. We will publish a new version of `turtle-cli` tomorrow. 🙂

If you’re such a hardcore user you could always use `turtle-cli` from a specific commit or branch, here eg. `ffef84e`, branch `sdk-33`. (https://docs.npmjs.com/files/package.json#git-urls-as-dependencies)

**Comment by sjchmiela** [comment]
@mackbrowne just so you know, changes of this PR has been published in `turtle-cli@0.8.0`.

**Pull request merged**
